# Generated by Django 4.2.7 on 2026-02-22 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("contenu", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("publie", models.BooleanField(default=False)),
                ("auteur", models.CharField(default="OIC", max_length=100)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-date_publication", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("sujet", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(default=django.utils.timezone.now)),
                ("lu", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("contenu", models.TextField()),
                ("afficher_dans_menu", models.BooleanField(default=True)),
                ("ordre_menu", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["ordre_menu", "titre"],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projets/"),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("planifie", "Planifié"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icone",
                    models.CharField(
                        help_text="Nom de l'icône (ex: fa-seedling)", max_length=100
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
